### ISSUE TITLE
Consider breaking out components?

### ISSUE THREAD

**Issue by crbinz** [JuliaSpace/SatelliteToolbox.jl#1]
Hi,

Congrats on the nice package, there is a lot of really great stuff in here! Have you considered moving things into smaller, dedicated packages? For instance, just from a quick browse of the code, I think the following components would lend themselves well to being standalone packages:

 - Geomagnetic field
 - Gravity field
 - the pure julia sgp4
 - potentially the frame transformations

I think most of these would also be useful to people who do not necessarily have interest in satellite mission analysis, and who otherwise would not know this functionality exists.

**Comment by ronisbr** [comment]
Hi @crbinz !

Thanks :)

Great suggestion. This package was originally used only inside INPE and, since it was not at METADATA, people had to clone the private repository manually. In this case, it seemed reasonable to have just one big package.

After the registration in METADATA, I will add some functionality that we already have but need to be ported to Julia and then I will start to think how can I break this package into smaller ones.

For sure, the frame transformations, IGRF, EGM, and SGP4 can go to standalone packages.

**Comment by ronisbr** [comment]
Hi @crbinz !

I finally could fix this very old issue :) Now, the ecosystem is split in smallr packages. If you install this one, it will install, load, and reexport all of them.

Thanks for the proposal and sorry for the delay :)

**Comment by crbinz** [comment]
Bravo! I think this is great for usability and extensibility. I hope I will get some time to experiment with it soon.
